# Generated by Django 4.0.6 on 2022-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_daily_data_description_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyDataJnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('brand_code', models.TextField()),
                ('company_id', models.TextField()),
                ('contract_issue', models.TextField()),
                ('name_jpn', models.TextField()),
                ('name_eng', models.TextField()),
                ('sell', models.TextField()),
                ('buy', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='daily_data',
            old_name='jpx_code',
            new_name='brand_code',
        ),
        migrations.RenameField(
            model_name='daily_data',
            old_name='right_val',
            new_name='buy',
        ),
        migrations.RenameField(
            model_name='daily_data',
            old_name='description',
            new_name='contract_issue',
        ),
        migrations.RenameField(
            model_name='daily_data',
            old_name='left_val',
            new_name='sell',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='company_id_right',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='label',
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
