# Generated by Django 4.0.6 on 2022-08-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_dailydatajnet_rename_jpx_code_daily_data_brand_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daily_data',
            new_name='dailyData',
        ),
    ]
