# Generated by Django 4.0.6 on 2022-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_daily_data_dailydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('daily_data', models.ManyToManyField(related_name='daily_data', to='home.dailydata')),
                ('daily_data_jnet', models.ManyToManyField(related_name='daily_data_jnet', to='home.dailydatajnet')),
            ],
        ),
    ]
