# Generated by Django 4.0.6 on 2022-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_chartdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='buy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='sell',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailydatajnet',
            name='buy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailydatajnet',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailydatajnet',
            name='sell',
            field=models.IntegerField(),
        ),
    ]
