# Generated by Django 4.0.6 on 2022-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_dailydata_buy_alter_dailydata_sell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dailydatajnet',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
