# Generated by Django 4.0.6 on 2022-08-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_linedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedata',
            name='is_topix',
            field=models.BooleanField(default=False),
        ),
    ]
