# Generated by Django 3.2.7 on 2021-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211020_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='company_id_right',
            field=models.TextField(blank=True, null=True),
        ),
    ]
