# Generated by Django 3.2.7 on 2021-11-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_daily_data_description_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_data',
            name='description_right',
        ),
    ]
